### ISSUE TITLE
老哥你这个下载的都不是大图啊

### ISSUE THREAD

**Issue by yoyoyosoro** [yukinotech/WeiboDL#1]
全是相册压过的缩略图，期待升级一下

**Comment by yukinotech** [comment]
能提供大图的URL和小图的URL的区别吗？
而且最近比较忙，可能下周有时间更新一下

**Comment by yukinotech** [comment]
> 全是相册压过的缩略图，期待升级一下

已经修复了，待会更新安装地址。也可以直接复制源码到游猴中。
