### ISSUE TITLE
大哥好像不能用了

### ISSUE THREAD

**Issue by xuanwohanser** [yukinotech/WeiboDL#10]
所有的博主界面都没法弹出了，能不能更新一下大佬

**Comment by yukinotech** [comment]
todo fix, 最近比较忙

**Comment by yukinotech** [comment]
不能用的博主链接发一下，目前已知问题是部分的博主界面无法弹出

**Comment by yukinotech** [comment]
P.S. url是这种类型的，https://weibo.com/u/xxxxxxxxxxx?tabtype=album。请在该url下刷新页面，重新加载脚本。点击切换到相册目前并不生效。以后有空会增加自动适配

**Comment by yukinotech** [comment]
因为没有反馈，暂时先关闭issue，如果后续有反馈会再次开启
