### ISSUE TITLE
下载

### ISSUE THREAD

**Issue by braless** [yukinotech/WeiboDL#3]
没有提供下载功能吗~ 只能批量建立任务下载连接了呀

**Comment by yukinotech** [comment]
你可以粘贴到迅雷或者IDM等专业下载软件，工具。

之所以不直接提供下载，是因为往往有的人的相册有上千张图片。如果我进行打包下载，从网络请求的并发上不太现实，从性能上可能会卡死浏览器。

目前暂不支持。
