### ISSUE TITLE
微博相册更新

### ISSUE THREAD

**Issue by JohnMatt2288** [yukinotech/WeiboDL#5]
Hi yukinotech,
非常喜欢您的这款脚本程序，对我帮助很大。
最近微博更新了相册页面显示，导致这个脚本无法使用，请问后续是否会对脚本进行更新呢？
再次感谢您的辛勤成果，祝好。
![Pic1](https://user-images.githubusercontent.com/115885638/195993909-f3ecad1c-29a0-4564-925f-8e62dcc88d45.png)

**Comment by whe1998** [comment]
这个脚本同样对我帮助非常大，最近有计划一次性下回自己的所有微博的照片，希望作者后续进行更新，愿意付费支持，非常感谢

**Comment by yukinotech** [comment]
> 这个脚本同样对我帮助非常大，最近有计划一次性下回自己的所有微博的照片，希望作者后续进行更新，愿意付费支持，非常感谢

前段时间比较忙，没有看到这个issue，今天抽空写了一个新版，可以试试，版本号>=2.0.0

**Comment by whe1998** [comment]
非常感谢！！！！！

**Comment by JohnMatt2288** [comment]
看到了，感觉比上一个版本更快捷方便了，非常感谢！



在 2022-11-19 15:59:16，"yukinotech" ***@***.***> 写道：

这个脚本同样对我帮助非常大，最近有计划一次性下回自己的所有微博的照片，希望作者后续进行更新，愿意付费支持，非常感谢

前段时间比较忙，没有看到这个issue，今天抽空写了一个新版，可以试试，版本号>=2.0.0

**Comment by yukinotech** [comment]
done
